### PR TITLE
Try making travis build rpms

### PR DESCRIPTION
**Pull request by exarkun**
Some minimal steps towards building RPMs on travis.

This doesn't actually work.  You can see the latest failures at https://travis-ci.org/exarkun/pyopenssl/jobs/47534352

I think some further changes are probably merited in setup.cfg (it's not clear to me that the build-requires declared there is actually correct, for example).

### CODE REVIEW

**Comment by JensTimmerman** [comment]
I believe this setup.cfg is correct, since the 'rpm' for the python headers is actually called python-devel on rpm based systems.
Since this rpm is not available on the travis-ci system the building of the rpm fails.

It might be a bit tricky to easily create an rpm on an apt based system like travis-ci.

**Comment by exarkun** [comment]
So, put another way, the packages that are declared as dependencies of the RPM have to be installed when building the RPM?  It does seem like that will make it difficult to build RPMs on travis's Ubuntu systems.

However, separately from that, I'm not sure pyopenssl _does_ depend on python-devel.  It used to, I'm sure, but it's no longer implemented in C and no longer requires compiling against Python.h.  What it does depend on is the cryptography project - which is not listed as a dependency.

**Comment by JensTimmerman** [comment]
Only the build dependencies need to be installed for building the rpm, 
I'm not sure if it needs all the dependencies listed in the setup.cfg, but I can try it out on a vm,
But it will always require `python-sphinx` to run the test you are going to add, because you're adding a test for creating the documentation correctly.

The cryptography project is defined as a runtime dependency, not a build dependency.
It will be defined as a dependency in the rpm and will be installed at install time on the machine the rpm is installed to, but it is not needed on the build server.
(it will end up as a dependency in the rpm because it's in the setup.py as `install_requires=["cryptography>=0.5.4", "six>=1.5.2"],`)

so: in setup.cfg: build_requires => build dependencies, needed to create the rpm
in setup.py: install_requires => runtime dependencies, not needed to create the rpm

**Comment by exarkun** [comment]
I'm sure that the inexorable march of history has rendered this PR irrelevant.

**Comment by JensTimmerman** [comment]
@exarkun thanks for the clean up, I'm not even sure anymore why you would make a pr to my fork of pyopenssl, I didn't even remember I had this fork, thanks for the clean up anwyway :)

**Pull request closed without merging**
